[package]
name = "sycamore-state"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen-test = "0.3"
wasm-bindgen = "0.2.83"

[dependencies.sycamore]
version = "0.8"

[features]
async = ["sycamore/suspense"]